CREATE TABLE sx_telephony_gateways (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  gateway_name VARCHAR(120) NOT NULL DEFAULT 'Dinstar UC2000-VE',
  gateway_host VARCHAR(253) NOT NULL,
  gateway_sip_port SMALLINT UNSIGNED NOT NULL DEFAULT 5061,
  gateway_sip_transport ENUM('tls') NOT NULL DEFAULT 'tls',
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  connection_status ENUM('not_tested','offline','online') NOT NULL DEFAULT 'not_tested',
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  configured_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_sx_telephony_gateway_tenant (tenant_id),
  KEY idx_sx_telephony_gateway_status (enabled,connection_status),
  CONSTRAINT fk_sx_telephony_gateway_tenant FOREIGN KEY (tenant_id) REFERENCES sx_tenants(id),
  CONSTRAINT fk_sx_telephony_gateway_configurer FOREIGN KEY (configured_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT ck_sx_telephony_gateway_port CHECK (gateway_sip_port BETWEEN 1 AND 65535)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sx_telephony_gateway_channels (
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  gateway_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  channel_no TINYINT UNSIGNED NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  inbound_enabled TINYINT(1) NOT NULL DEFAULT 0,
  outbound_enabled TINYINT(1) NOT NULL DEFAULT 0,
  inbound_did VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
  inbound_queue_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  updated_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  updated_at DATETIME(3) NULL,
  PRIMARY KEY (tenant_id,gateway_id,channel_no),
  UNIQUE KEY uq_sx_telephony_gateway_channel_did (inbound_did),
  KEY idx_sx_telephony_gateway_channel_queue (tenant_id,inbound_queue_id),
  CONSTRAINT fk_sx_telephony_gateway_channel_gateway FOREIGN KEY (gateway_id) REFERENCES sx_telephony_gateways(id),
  CONSTRAINT fk_sx_telephony_gateway_channel_tenant FOREIGN KEY (tenant_id) REFERENCES sx_tenants(id),
  CONSTRAINT fk_sx_telephony_gateway_channel_queue FOREIGN KEY (tenant_id,inbound_queue_id) REFERENCES sx_telephony_queues(tenant_id,id),
  CONSTRAINT fk_sx_telephony_gateway_channel_actor FOREIGN KEY (updated_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT ck_sx_telephony_gateway_channel_number CHECK (channel_no BETWEEN 1 AND 4),
  CONSTRAINT ck_sx_telephony_gateway_channel_policy CHECK (enabled=1 OR (inbound_enabled=0 AND outbound_enabled=0)),
  CONSTRAINT ck_sx_telephony_gateway_channel_inbound CHECK (inbound_enabled=0 OR (inbound_did IS NOT NULL AND inbound_queue_id IS NOT NULL)),
  CONSTRAINT ck_sx_telephony_gateway_channel_did CHECK (inbound_did IS NULL OR inbound_did REGEXP '^\\+[1-9][0-9]{7,14}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
