-- Verified owner destinations and idempotent report delivery attempts.
CREATE TABLE sx_training_report_verifications (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  schedule_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  schedule_revision INT UNSIGNED NOT NULL,
  channel ENUM('email','whatsapp') NOT NULL,
  request_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  destination_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  challenge_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status ENUM('pending','verified','expired','superseded','failed','unknown','locked') NOT NULL DEFAULT 'pending',
  attempt_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  expires_at DATETIME(3) NOT NULL,
  sent_at DATETIME(3) NULL,
  verified_at DATETIME(3) NULL,
  created_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_training_report_verification_request (tenant_id,request_key),
  KEY idx_training_report_verification_rate (tenant_id,schedule_id,channel,created_at),
  KEY idx_training_report_verification_active (tenant_id,schedule_id,channel,status,expires_at),
  CONSTRAINT fk_training_report_verification_schedule FOREIGN KEY (tenant_id,schedule_id) REFERENCES sx_training_report_schedules(tenant_id,id),
  CONSTRAINT fk_training_report_verification_creator FOREIGN KEY (created_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT ck_training_report_verification_attempts CHECK (attempt_count<=5),
  CONSTRAINT ck_training_report_verification_status CHECK ((status='verified' AND verified_at IS NOT NULL) OR (status<>'verified' AND verified_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sx_training_report_deliveries (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  report_run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  schedule_revision INT UNSIGNED NOT NULL,
  channel ENUM('email','whatsapp') NOT NULL,
  status ENUM('queued','processing','retry','accepted','failed','suppressed','unknown') NOT NULL DEFAULT 'queued',
  attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
  available_at DATETIME(3) NOT NULL,
  lease_owner VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,
  lease_expires_at DATETIME(3) NULL,
  provider_message_id VARCHAR(191) NULL,
  last_error_code VARCHAR(100) NULL,
  accepted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_training_report_delivery_channel (tenant_id,report_run_id,channel),
  KEY idx_training_report_delivery_ready (status,available_at,created_at),
  KEY idx_training_report_delivery_tenant_history (tenant_id,report_run_id,status),
  CONSTRAINT fk_training_report_delivery_run FOREIGN KEY (tenant_id,report_run_id) REFERENCES sx_training_report_runs(tenant_id,id),
  CONSTRAINT ck_training_report_delivery_lease CHECK ((status='processing' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL) OR (status<>'processing' AND lease_owner IS NULL AND lease_expires_at IS NULL)),
  CONSTRAINT ck_training_report_delivery_accepted CHECK ((status='accepted' AND accepted_at IS NOT NULL) OR (status<>'accepted' AND accepted_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
