-- Verified manual payment records and one immutable receipt per posted payment.
CREATE TABLE sx_training_payments (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  invoice_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  method ENUM('cash','bank_transfer','cheque','other') NOT NULL,
  external_reference VARCHAR(200) NULL,
  recording_note VARCHAR(1000) NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  amount_minor BIGINT UNSIGNED NOT NULL,
  unapplied_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  received_at DATETIME(3) NOT NULL,
  status ENUM('pending_verification','posted','rejected') NOT NULL DEFAULT 'pending_verification',
  recorded_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  verified_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  verified_at DATETIME(3) NULL,
  verification_reason VARCHAR(1000) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_training_payment_tenant_id (tenant_id,id),
  UNIQUE KEY uq_training_payment_request (tenant_id,request_key),
  KEY idx_training_payment_invoice (tenant_id,invoice_id,status,received_at),
  KEY idx_training_payment_reference (tenant_id,method,external_reference),
  KEY idx_training_payment_review (tenant_id,status,created_at),
  CONSTRAINT fk_training_payment_tenant FOREIGN KEY (tenant_id) REFERENCES sx_tenants(id),
  CONSTRAINT fk_training_payment_invoice FOREIGN KEY (tenant_id,invoice_id) REFERENCES sx_training_invoices(tenant_id,id),
  CONSTRAINT fk_training_payment_recorder FOREIGN KEY (recorded_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT fk_training_payment_verifier FOREIGN KEY (verified_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT ck_training_payment_amount CHECK (amount_minor>0 AND unapplied_minor<=amount_minor),
  CONSTRAINT ck_training_payment_verification CHECK ((status='posted' AND verified_by_identity_id IS NOT NULL AND verified_at IS NOT NULL) OR (status<>'posted' AND verified_by_identity_id IS NULL AND verified_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sx_training_payment_allocations (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payment_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  invoice_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  installment_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  amount_minor BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_training_payment_installment (tenant_id,payment_id,installment_id),
  KEY idx_training_payment_allocation_invoice (tenant_id,invoice_id,created_at),
  KEY idx_training_payment_allocation_installment (tenant_id,installment_id),
  CONSTRAINT fk_training_payment_allocation_tenant FOREIGN KEY (tenant_id) REFERENCES sx_tenants(id),
  CONSTRAINT fk_training_payment_allocation_payment FOREIGN KEY (tenant_id,payment_id) REFERENCES sx_training_payments(tenant_id,id),
  CONSTRAINT fk_training_payment_allocation_invoice FOREIGN KEY (tenant_id,invoice_id) REFERENCES sx_training_invoices(tenant_id,id),
  CONSTRAINT fk_training_payment_allocation_installment FOREIGN KEY (tenant_id,installment_id) REFERENCES sx_training_installments(tenant_id,id),
  CONSTRAINT ck_training_payment_allocation_amount CHECK (amount_minor>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sx_training_receipts (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payment_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  receipt_number VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  invoice_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  amount_minor BIGINT UNSIGNED NOT NULL,
  payer_name_snapshot VARCHAR(255) NOT NULL,
  recipient_email_snapshot VARCHAR(254) NOT NULL,
  method_snapshot ENUM('cash','bank_transfer','cheque','other') NOT NULL,
  external_reference_snapshot VARCHAR(200) NULL,
  received_at DATETIME(3) NOT NULL,
  issued_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_training_receipt_tenant_id (tenant_id,id),
  UNIQUE KEY uq_training_receipt_payment (tenant_id,payment_id),
  UNIQUE KEY uq_training_receipt_number (tenant_id,receipt_number),
  CONSTRAINT fk_training_receipt_tenant FOREIGN KEY (tenant_id) REFERENCES sx_tenants(id),
  CONSTRAINT fk_training_receipt_payment FOREIGN KEY (tenant_id,payment_id) REFERENCES sx_training_payments(tenant_id,id),
  CONSTRAINT fk_training_receipt_invoice FOREIGN KEY (tenant_id,invoice_id) REFERENCES sx_training_invoices(tenant_id,id),
  CONSTRAINT ck_training_receipt_amount CHECK (amount_minor>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
