CREATE TABLE sx_telephony_calls (
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  direction ENUM('inbound','outbound') NOT NULL,
  status ENUM('starting','ringing','connected','ended','failed') NOT NULL,
  gateway_channel_no TINYINT UNSIGNED NOT NULL,
  leased_channel_no TINYINT UNSIGNED NULL,
  inbound_queue_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  started_by_membership_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  answered_by_membership_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  inbound_channel_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  bridge_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  answered_at DATETIME(3) NULL,
  ended_at DATETIME(3) NULL,
  duration_seconds INT UNSIGNED NULL,
  end_reason VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (tenant_id,id),
  UNIQUE KEY uq_sx_telephony_call_inbound_channel (inbound_channel_id),
  UNIQUE KEY uq_sx_telephony_call_active_gateway_channel (leased_channel_no),
  KEY idx_sx_telephony_calls_tenant_started (tenant_id,started_at,id),
  KEY idx_sx_telephony_calls_queue_status (tenant_id,inbound_queue_id,status),
  CONSTRAINT fk_sx_telephony_call_tenant FOREIGN KEY (tenant_id) REFERENCES sx_tenants(id),
  CONSTRAINT fk_sx_telephony_call_queue FOREIGN KEY (tenant_id,inbound_queue_id) REFERENCES sx_telephony_queues(tenant_id,id),
  CONSTRAINT fk_sx_telephony_call_starter FOREIGN KEY (tenant_id,started_by_membership_id) REFERENCES sx_memberships(tenant_id,id),
  CONSTRAINT fk_sx_telephony_call_answerer FOREIGN KEY (tenant_id,answered_by_membership_id) REFERENCES sx_memberships(tenant_id,id),
  CONSTRAINT ck_sx_telephony_call_channel CHECK (gateway_channel_no BETWEEN 1 AND 4 AND (leased_channel_no IS NULL OR leased_channel_no BETWEEN 1 AND 4)),
  CONSTRAINT ck_sx_telephony_call_duration CHECK (duration_seconds IS NULL OR duration_seconds <= 86400)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sx_telephony_call_legs (
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  call_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asterisk_channel_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  leg_role ENUM('caller','agent','gateway') NOT NULL,
  device_kind ENUM('mobile','browser','gateway') NOT NULL,
  membership_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  status ENUM('originating','ringing','connected','ended','failed') NOT NULL,
  started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  answered_at DATETIME(3) NULL,
  ended_at DATETIME(3) NULL,
  end_reason VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL,
  PRIMARY KEY (tenant_id,id),
  UNIQUE KEY uq_sx_telephony_call_leg_asterisk_channel (asterisk_channel_id),
  KEY idx_sx_telephony_call_legs_call (tenant_id,call_id,status),
  KEY idx_sx_telephony_call_legs_member (tenant_id,membership_id,status),
  CONSTRAINT fk_sx_telephony_call_leg_call FOREIGN KEY (tenant_id,call_id) REFERENCES sx_telephony_calls(tenant_id,id),
  CONSTRAINT fk_sx_telephony_call_leg_member FOREIGN KEY (tenant_id,membership_id) REFERENCES sx_memberships(tenant_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
