-- Sale review requests are immutable commercial snapshots. Approval is not invoice issue or enrollment.
CREATE TABLE IF NOT EXISTS sx_training_sale_reviews (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  legacy_uid_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  legacy_uid VARCHAR(999) NOT NULL,
  lead_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  revision INT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  course_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  offer_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  batch_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  course_name_en VARCHAR(200) NOT NULL,
  course_name_ar VARCHAR(200) NOT NULL,
  offer_version INT UNSIGNED NOT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  price_minor BIGINT UNSIGNED NOT NULL,
  registration_fee_minor BIGINT UNSIGNED NOT NULL,
  discount_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  net_minor BIGINT UNSIGNED NOT NULL,
  learner_name VARCHAR(255) NOT NULL,
  payer_name VARCHAR(255) NOT NULL,
  payer_email VARCHAR(254) NULL,
  payer_phone VARCHAR(40) NULL,
  invoice_email VARCHAR(254) NOT NULL,
  terms_snapshot VARCHAR(2000) NOT NULL,
  installments JSON NOT NULL,
  lead_updated_at_snapshot DATETIME(3) NOT NULL,
  submitted_by_type ENUM('user','agent') NOT NULL,
  submitted_by_id VARCHAR(191) NOT NULL,
  decided_by_type ENUM('user','agent') NULL,
  decided_by_id VARCHAR(191) NULL,
  decision_reason VARCHAR(1000) NULL,
  decided_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_sx_sale_review_request_key (tenant_id,request_key),
  UNIQUE KEY uq_sx_sale_review_tenant_id (tenant_id,id),
  KEY idx_sx_sale_review_lead (tenant_id,lead_id,created_at),
  KEY idx_sx_sale_review_queue (tenant_id,status,created_at),
  CONSTRAINT fk_sx_sale_review_tenant FOREIGN KEY (tenant_id) REFERENCES sx_tenants(id),
  CONSTRAINT fk_sx_sale_review_course FOREIGN KEY (tenant_id,course_id) REFERENCES sx_training_courses(tenant_id,id),
  CONSTRAINT fk_sx_sale_review_offer FOREIGN KEY (tenant_id,offer_id) REFERENCES sx_training_offers(tenant_id,id),
  CONSTRAINT fk_sx_sale_review_batch FOREIGN KEY (tenant_id,batch_id) REFERENCES sx_training_batches(tenant_id,id),
  CONSTRAINT ck_sx_sale_review_discount CHECK (discount_minor <= price_minor),
  CONSTRAINT ck_sx_sale_review_totals CHECK (net_minor = price_minor + registration_fee_minor - discount_minor)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
