-- Manual refunds of unapplied customer deposits; posted receipts stay immutable.
CREATE TABLE sx_training_refunds (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payment_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  invoice_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  amount_minor BIGINT UNSIGNED NOT NULL,
  reason VARCHAR(1000) NOT NULL,
  status ENUM('pending_approval','approved','completed','rejected') NOT NULL DEFAULT 'pending_approval',
  requested_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reviewed_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  reviewed_at DATETIME(3) NULL,
  review_reason VARCHAR(1000) NULL,
  completion_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  completion_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  completed_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  completed_at DATETIME(3) NULL,
  method ENUM('cash','bank_transfer') NULL,
  external_reference VARCHAR(200) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_training_refund_tenant_id (tenant_id,id),
  UNIQUE KEY uq_training_refund_request (tenant_id,request_key),
  UNIQUE KEY uq_training_refund_completion (tenant_id,completion_key),
  KEY idx_training_refund_payment (tenant_id,payment_id,status),
  KEY idx_training_refund_invoice (tenant_id,invoice_id,created_at),
  KEY idx_training_refund_queue (tenant_id,status,created_at),
  CONSTRAINT fk_training_refund_payment FOREIGN KEY (tenant_id,payment_id) REFERENCES sx_training_payments(tenant_id,id),
  CONSTRAINT fk_training_refund_invoice FOREIGN KEY (tenant_id,invoice_id) REFERENCES sx_training_invoices(tenant_id,id),
  CONSTRAINT fk_training_refund_requester FOREIGN KEY (requested_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT fk_training_refund_reviewer FOREIGN KEY (reviewed_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT fk_training_refund_completer FOREIGN KEY (completed_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT ck_training_refund_amount CHECK (amount_minor>0),
  CONSTRAINT ck_training_refund_review CHECK ((status='pending_approval' AND reviewed_at IS NULL AND reviewed_by_identity_id IS NULL) OR (status<>'pending_approval' AND reviewed_at IS NOT NULL AND reviewed_by_identity_id IS NOT NULL)),
  CONSTRAINT ck_training_refund_completion CHECK ((status='completed' AND completed_at IS NOT NULL AND completed_by_identity_id IS NOT NULL AND completion_key IS NOT NULL AND completion_hash IS NOT NULL AND method IS NOT NULL AND external_reference IS NOT NULL) OR (status<>'completed' AND completed_at IS NULL AND completed_by_identity_id IS NULL AND completion_key IS NULL AND completion_hash IS NULL AND method IS NULL AND external_reference IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
