-- Versioned training courses, priced offers and scheduled batches.
CREATE TABLE sx_training_courses (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  code VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  name_en VARCHAR(200) NOT NULL,
  name_ar VARCHAR(200) NOT NULL,
  description_en TEXT NOT NULL,
  description_ar TEXT NOT NULL,
  duration_value SMALLINT UNSIGNED NOT NULL,
  duration_unit ENUM('hours','days','weeks','months') NOT NULL,
  delivery_mode ENUM('in_person','online','hybrid') NOT NULL,
  status ENUM('draft','active','retired') NOT NULL DEFAULT 'draft',
  revision INT UNSIGNED NOT NULL DEFAULT 1,
  created_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  updated_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_sx_training_course_tenant_id (tenant_id,id),
  UNIQUE KEY uq_sx_training_course_code (tenant_id,code),
  KEY idx_sx_training_course_status (tenant_id,status,updated_at),
  CONSTRAINT fk_sx_training_course_tenant FOREIGN KEY (tenant_id) REFERENCES sx_tenants(id),
  CONSTRAINT fk_sx_training_course_creator FOREIGN KEY (created_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT fk_sx_training_course_updater FOREIGN KEY (updated_by_identity_id) REFERENCES sx_identities(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sx_training_offers (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  course_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version INT UNSIGNED NOT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'QAR',
  price_minor BIGINT UNSIGNED NOT NULL,
  registration_fee_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  valid_from DATE NULL,
  valid_until DATE NULL,
  inclusions JSON NOT NULL,
  status ENUM('active','retired') NOT NULL DEFAULT 'active',
  created_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_sx_training_offer_tenant_id (tenant_id,id),
  UNIQUE KEY uq_sx_training_offer_version (tenant_id,course_id,version),
  KEY idx_sx_training_offer_active (tenant_id,course_id,status,version),
  CONSTRAINT fk_sx_training_offer_course FOREIGN KEY (tenant_id,course_id) REFERENCES sx_training_courses(tenant_id,id),
  CONSTRAINT fk_sx_training_offer_creator FOREIGN KEY (created_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT ck_sx_training_offer_dates CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sx_training_batches (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  course_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  code VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  language_code VARCHAR(12) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  capacity SMALLINT UNSIGNED NOT NULL,
  reserved_seats SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('scheduled','open','full','completed','cancelled') NOT NULL DEFAULT 'scheduled',
  created_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_sx_training_batch_tenant_id (tenant_id,id),
  UNIQUE KEY uq_sx_training_batch_code (tenant_id,code),
  KEY idx_sx_training_batch_dates (tenant_id,course_id,status,starts_on),
  CONSTRAINT fk_sx_training_batch_course FOREIGN KEY (tenant_id,course_id) REFERENCES sx_training_courses(tenant_id,id),
  CONSTRAINT fk_sx_training_batch_creator FOREIGN KEY (created_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT ck_sx_training_batch_dates CHECK (ends_on >= starts_on),
  CONSTRAINT ck_sx_training_batch_capacity CHECK (capacity > 0 AND reserved_seats <= capacity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
