-- Tenant-specific finance policy versions. Approval is restricted to an authenticated accountant identity.
CREATE TABLE sx_training_finance_policies (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version INT UNSIGNED NOT NULL,
  revision INT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('draft','pending_accountant','approved','rejected','superseded') NOT NULL DEFAULT 'draft',
  jurisdiction CHAR(2) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'QA',
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'QAR',
  legal_name VARCHAR(200) NOT NULL DEFAULT '',
  legal_registration_number VARCHAR(100) NULL,
  legal_address VARCHAR(1000) NULL,
  invoice_prefix VARCHAR(16) NOT NULL DEFAULT '',
  tax_mode ENUM('unset','no_tax','exclusive','inclusive') NOT NULL DEFAULT 'unset',
  tax_rate_bps SMALLINT UNSIGNED NULL,
  revenue_method ENUM('unset','deferred_until_delivery','over_time') NOT NULL DEFAULT 'unset',
  issue_approver ENUM('unset','owner','accountant') NOT NULL DEFAULT 'unset',
  manual_second_approval_above_minor BIGINT UNSIGNED NULL,
  created_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  submitted_at DATETIME(3) NULL,
  reviewed_by_identity_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  reviewed_by_role ENUM('accountant') NULL,
  reviewed_at DATETIME(3) NULL,
  review_reason VARCHAR(1000) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_sx_finance_policy_tenant_id (tenant_id,id),
  UNIQUE KEY uq_sx_finance_policy_version (tenant_id,version),
  KEY idx_sx_finance_policy_status (tenant_id,status,version),
  KEY idx_sx_finance_policy_reviewer (tenant_id,reviewed_by_identity_id,reviewed_at),
  CONSTRAINT fk_sx_finance_policy_tenant FOREIGN KEY (tenant_id) REFERENCES sx_tenants(id),
  CONSTRAINT fk_sx_finance_policy_creator FOREIGN KEY (created_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT fk_sx_finance_policy_reviewer FOREIGN KEY (reviewed_by_identity_id) REFERENCES sx_identities(id),
  CONSTRAINT ck_sx_finance_policy_tax_rate CHECK (tax_rate_bps IS NULL OR tax_rate_bps <= 10000),
  CONSTRAINT ck_sx_finance_policy_review CHECK ((status IN ('approved','rejected','superseded') AND reviewed_by_identity_id IS NOT NULL AND reviewed_by_role='accountant' AND reviewed_at IS NOT NULL) OR (status NOT IN ('approved','rejected','superseded') AND reviewed_by_identity_id IS NULL AND reviewed_by_role IS NULL AND reviewed_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
